-- AlterTable
ALTER TABLE "users" ALTER COLUMN "phone" DROP NOT NULL,
ALTER COLUMN "address" DROP NOT NULL,
ALTER COLUMN "sim_number" DROP NOT NULL,
ALTER COLUMN "sim_image" DROP NOT NULL,
ALTER COLUMN "avatar" DROP NOT NULL;
